### ISSUE TITLE
Add $number->round

### ISSUE THREAD

**Issue by schwern** [evalEmpire/perl5i#95]
We have round_up and round_down but not round.

First cut simply rounds to nearest integer.  Tie breaking is half up (ie. 1.5->round == 2)

Additional features:
- specify tie breaking mechanic
- specify rounding increment

Make round() take a hash of options.

See https://secure.wikimedia.org/wikipedia/en/wiki/Rounding#Rounding_to_a_specified_increment

**Comment by van-de-bugger** [comment]
What is "round"? [Wikipedia article](https://en.wikipedia.org/wiki/Rounding#Tie-breaking) gives 6 variants of rounding. Which one is "round"? Is it an alias for round_up, round_down or one of four alternatives (toward zero, away from zero, to even, to odd)?

**Comment by notbenh** [comment]
num->round is true round, ie 0.49->round is 0 where 0.5->round is 1. I feel that the docs say that clearly enough though I think that any documentation patches are very welcome. The round is implemented here, if that helps:
https://github.com/evalEmpire/perl5i/blob/master/lib/perl5i/0/SCALAR.pm#L130

**Comment by van-de-bugger** [comment]
> num->round is true round

Sorry, I have no idea what is "true round". 

> I feel that the docs say that clearly enough

But it is not. [The documentation](https://metacpan.org/pod/perl5i#round) says "Round to the nearest integer." If fractionnal part is exactly 0.5, there are two nearest integer numbers, and both of them are equally nearest. It it clearly explained in [Wikipedia article](https://en.wikipedia.org/wiki/Rounding#Tie-breaking).

> documentation patches are very welcome

Sorry again, I cannot provide documentation patch because I have no idea about your intent. I have provided a link to [Wikipedia article](https://en.wikipedia.org/wiki/Rounding#Tie-breaking), which explains the problem and describes 6 possible solutions, and asked which one you are implemented (or going to implement), but I do not see answer. "True rounding" is not an answer, sorry.

> The round is implemented here, if that helps: https://github.com/evalEmpire/perl5i/blob/master/lib/perl5i/0/SCALAR.pm#L130

Thanks for the link. I see perl5i round_up is a synonym for ceil, and round_down is a synonym for floor. Sorry again, but it is **completely wrong**. Here are proper implementation of round_up and round_down (in plain perl):

    sub round_up($) { return floor( $_[ 0 ] + 0.5 ); }
    sub round_down($) { return ceil( $_[ 0 ] - 0.5 ); }

Implementation of round is a... sorry, again. Very sorry. 

Again, please see [Wikipedia article](https://en.wikipedia.org/wiki/Rounding#Tie-breaking).

**Comment by notbenh** [comment]
I am sorry that you feel this way though in an effort to better understand I would be curious to try a few examples to see if we might just be talking past each other. 

For example if I was to round 1.1 what should the outcome be? Would you be surprised if you got 0.6 or 1.6? What is expected outcome when you round 2.9? Is the correct answer 3.4? Possibly 2.4? Or are there other answers that you expect to get? 

With this in mind do you have any perl5i code that shows that the way that round is implemented breaks these expectations?
